<?php
$l['number'] 						= 'Reciept No.';
$l['date'] 							= 'Cash Date';
$l['due'] 							= 'Time';
$l['to'] 							= 'Cash From';
$l['from'] 							= 'Cash To';
$l['product'] 						= 'Payment';
$l['amount'] 						= 'Type';
$l['price'] 						= 'Date';
$l['discount'] 						= 'Discount';
$l['vat'] 							= 'Tax';
$l['total'] 						= 'Total';
$l['page'] 							= 'Page';
$l['page_of'] 						= 'of';
?>